### ISSUE TITLE
web/client Empty Farm Lightbox

### ISSUE THREAD

**Issue by gumbyscout** [nictuku/stardew-rocks#33]
Need to handle when a 'History' isn't available for a specific farm and let the user know & just fill the light box with the thumbnail.

**Comment by nictuku** [comment]
Isn't the lightbox related to zooming? Not sure why History is relevant.

**Comment by gumbyscout** [comment]
The history numbers are used to grab past screenshots, if a farm doesn't have them, then currently, the lamba that returns a bunch of screenshot urls, returns an empty array, which leaves an empty lightbox.

**Comment by gumbyscout** [comment]
This has been resolved without my intervention i.e. sending History in the response on prod, closing this ticket.

**Comment by nictuku** [comment]
Empty lightboxes still appear, but that's when the images are slow to load. Which is working as intended.
